Bookers2/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
  resources :book_comments, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
end
  resources :users, only: [:index, :show, :edit, :update]

  get '/home/about', to: 'homes#about'


end

Bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers2/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

Bookers2/app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

 validates :comment, presence: true

end

Bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  
end

Bookers2/app/models/user.rb
class User < ApplicationRecord
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


 has_many :books, dependent: :destroy
 has_many :book_comments, dependent: :destroy
 has_many :favorites, dependent: :destroy
 
 attachment :profile_image

end

Bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :passward])

    devise_parameter_sanitizer.permit(
      :sign_in,
      keys: [:name, :password])
  end
end

Bookers2/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
      redirect_to book_path(book)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment) .permit(:comment)

  end

end

Bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!
    before_action :check_current_user, only: [:edit, :update, :destroy]

    def index
        @books = Book.all
    end

    def create
        @book_new = Book.new(book_params)
        @book_new.user_id = current_user.id
        if @book_new.save
            flash[:notice] = "You have created book successfully."
            redirect_to book_path(@book_new.id)
        else
            @books = Book.all
            @user = User.find(current_user.id)
            render("/books/index")
        end
    end

    def edit
        @book = Book.find(params[:id])
    end

    def show
        @book = Book.find(params[:id])
        @book_comment = BookComment.new
    end

    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
            flash[:notice] = "You have updated book successfully."
            redirect_to book_path(@book.id)
        else
            render ("/books/edit")
        end
    end

    def destroy
        book = Book.find(params[:id])
        flash[:notice] = "Book was successfully destroyed."
        book.destroy
        redirect_to("/books")
    end

    private
    def book_params
      params.require(:book).permit(:title, :body)
    end

    def check_current_user
        unless Book.find(params[:id]).user == current_user
            redirect_to books_path
        end
    end
end

Bookers2/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: books_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: books_path)
  end
end

Bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

Bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :check_current_user, only: [:edit, :update]

    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
        @books = @user.books
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "You have updated user successfully."
            redirect_to user_path(@user.id)
        else
            render ("/users/edit")
        end
    end

    private
    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end

    def check_current_user
        unless User.find(params[:id]) == current_user
            redirect_to user_path(current_user.id)
        end
    end
end

Bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers2/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

Bookers2/app/helpers/books_helper.rb
module BooksHelper
end

Bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

Bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

Bookers2/app/helpers/users_helper.rb
module UsersHelper
end

Bookers2/app/views/books/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
            <h1>Editing Book</h1>
            <% if @book.errors.any? %>
                <div id="error_explanation">
                    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
                    <ul>
                        <% @book.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
            <%= form_with model:@book, local:true do |f| %>
                <div class="form-group">
                    <label for="book_title">Title</label>
                    <%= f.text_field :title, class: "form-control" %>
                </div>
                <div class="form-group">
                    <label for="book_opinion">Opinion</label>
                    <%= f.text_area :body, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.submit "Update Book", class:"btn btn-success" %>
                </div>
            <% end %>
            <%= link_to "Show", book_path(@book.id) %> |
            <%= link_to "Back", books_path %>
        </div>
    </div>
</div

Bookers2/app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <%= render 'common/left_side', user: current_user %>
        </div>
        <!-- Bookリスト -->
        <div class="col-md-8 offset-md-1">
            <h2>Books</h2>
            <table class="table table-hover table-inverse">
                <thead>
                    <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Opinion</th>
                        <th colspan="5"></th>
                    </tr>
                </thead>
                <tbody>
                    <% @books.each do |book| %>
                        <tr>
                            <td>
                                <%= link_to user_path(book.user_id) do %>
                                    <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
                                <% end %>
                            </td>
                            <td>
                                <%= link_to book_path(book.id) do %>
                                    <%= book.title %>
                                <% end %>
                            </td>
                            <td>
                                <%= book.body %>
                            </td>
                            <td>
                                <% if book.favorited_by?(current_user) %>
                             <p>
                                 <%= link_to book_favorites_path(book.id), method: :delete do %>
                                 ♥<%= book.favorites.count %>
                                 <% end %>
                             </p>
                             <% else %>
                             <p>
                                <%= link_to book_favorites_path(book.id), method: :post do %>
                                ♡<%= book.favorites.count %>
                                <% end %>
                            </p>
                            <% end %>
                            </td>
                            <td>
                                <p><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></p>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

Bookers2/app/views/books/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <%= render 'common/left_side', user: @book.user %>
        </div>
        <div class="col-md-8 offset-md-1">
            <h2>Book detail</h2>
            <table class="table">
                <tbody>
                    <tr>
                        <td>
                            <%= link_to user_path(@book.user.id) do %>
                                <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %><br>
                                <%= @book.user.name %>
                            <% end %>
                        </td>
                        <td>
                            <%= link_to book_path(@book.id) do %>
                                <%= @book.title %>
                            <% end %>
                        </td>
                        <td>
                            <%= @book.body %>
                        </td>
                        <td>
                            <% if @book.favorited_by?(current_user) %>
                             <p>
                                 <%= link_to book_favorites_path(@book.id), method: :delete do %>
                                 ♥<%= @book.favorites.count %>
                                 <% end %>
                             </p>
                             <% else %>
                             <p>
                                <%= link_to book_favorites_path(@book.id), method: :post do %>
                                ♡<%= @book.favorites.count %>
                                <% end %>
                            </p>
                            <% end %>
                        </td>
                        <td>
                            <p>コメント数：<%= @book.book_comments.count %></p>
                        </td>
                        <% if @book.user.id == current_user.id %>
                            <td>
                                <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %>
                            </td>
                            <td>
                                <%= link_to "Destroy", book_path, method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-sm btn-danger" %>
                            </td>
                        <% end %>
                    </tr>
                    <tr>
                        <td>
                            <div class="comments">

                                <% @book.book_comments.each do |book_comment| %>
                                 <%= attachment_image_tag book_comment.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
                                 <%= book_comment.comment %>
                                 <% if book_comment.user == current_user %>
                                    <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-sm btn-danger" %>
                                 <% end %>
                              <% end %>
                            </div>
                            <div class="new-comment">
                              <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
                               <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
                               <%= f.submit "送信" %>
                              <% end %>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

Bookers2/app/views/common/_left_side.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
<table class="table">
    <tbody>
        <tr></tr>
        <tr>
            <th>name</th>
            <th><%= user.name %></th>
        </tr>
        <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
        </tr>
    </tbody>
</table>
<div class="row">
    <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block fas fa-user-cog" do %>
    <% end %>
</div>
<!-- Book新規登録 -->
<h2 class="mt-3">New book</h2>
<%= form_with model: Book.new, local:true do |f| %>
    <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.submit "Create Book", class: "btn btn-success" %>
    </div>
<% end %>

Bookers2/app/views/homes/about.html.erb
<p id="notice"></p>
    <div class="container">
        <div class="row">
            <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
        </div>
    </div>

Bookers2/app/views/homes/top.html.erb
<p id="notice"></p>
    <div class="container">
        <div class="row">
            <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
                <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
                <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
                <p>you can share and exchange  your opinions , inpressions , and emotions</p>
                <p> about various books!</p>
                <div class="btn-wrapper col-10 mx-auto">
                    <div class="row">
                        <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
                    </div>
                    <div class="row">
                        <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
                    </div>
                </div>
            </div>
        </div>
    </div>

Bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", "/", class:"navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user.id) do %>
                    <i class="fas fa-home nav-link text-light"> Home</i>
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path do %>
                    <i class="fas fa-users nav-link text-light"> Users</i>
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path do %>
                    <i class="fas fa-book-open nav-link text-light"> Books</i>
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fas fa-sign-out-alt nav-link text-light"> logout</i>
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path do %>
                    <i class="fas fa-home nav-link text-light"> Home</i>
                  <% end %>
                </li>
                <li>
                  <%= link_to home_about_path do %>
                    <span class="fas fa-link nav-link text-light"> About</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path do %>
                    <i class="fas fa-user-plus nav-link text-light"> sign up</i>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path do %>
                    <i class="fas fa-sign-in-alt nav-link text-light"> login</i>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <p id="notice"><%= flash[:notice] %></p>
      <div class="container px-5 px-sm-0">
        <% if @book_new && @book_new.errors.any? %>
          <div id="error_explanation">
            <h3><%= @book_new.errors.count %> errors prohibited this obj from being saved:</h3>
            <ul>
              <% @book_new.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>

    <%= yield %>

    <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

  </body>
</html>

Bookers2/app/views/users/edit.html.erb
<main>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
                <h2>User info</h2>
                <%= form_with model: @user, local:true do |f| %>
                    <% if @user.errors.any? %>
                        <div id="error_explanation">
                            <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
                            <ul>
                                <% @user.errors.full_messages.each do |message| %>
                                    <li><%= message %></li>
                                <% end %>
                            </ul>
                        </div>
                    <% end %>
                    <div class="form-group">
                        <label for="user_name">Name</label>
                        <%= f.text_field :name, class: "form-control" %>
                    </div>
                    <div class="form-group">
                        <label for="user_image">Image</label>
                        <%= f.attachment_field :profile_image, class: "form-control-file" %>
                    </div>
                    <div class="form-group">
                        <label for="user_introduction">Introduction</label>
                        <%= f.text_area :introduction, class: "form-control" %>
                    </div>
                    <div class="form-group">
                        <%= f.submit "Update User", class: "btn btn-secondary" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</main>

Bookers2/app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <%= render 'common/left_side', user: current_user %>
        </div>
        <div class="col-md-8 offset-md-1">
            <h2>Users</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>image</th>
                        <th>name</th>
                        <th colspan="3"></th>
                    </tr>
                </thead>
                <tbody>
                    <% @users.each do |user| %>
                        <tr>
                            <td>
                                <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
                            </td>
                            <td>
                                <%= user.name %>
                            </td>
                            <td>
                                <%= link_to "Show", user_path(user.id) %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

Bookers2/app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <%= render 'common/left_side', user: @user %>
        </div>
        <!-- Bookリスト -->
        <div class="col-md-8 offset-md-1">
            <h2>Books</h2>
            <table class="table table-hover table-inverse">
                <thead>
                    <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Opinion</th>
                        <th colspan="3"></th>
                    </tr>
                </thead>
                <tbody>
                    <% @books.each do |book| %>
                        <tr>
                            <td>
                                <%= link_to user_path(book.user_id) do %>
                                    <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
                                <% end %>
                            </td>
                            <td>
                                <%= link_to book_path(book.id) do %>
                                    <%= book.title %>
                                <% end %>
                            </td>
                            <td>
                                <%= book.body %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>